### ISSUE TITLE
Discrepancy in User Identity Association During Registration and SEP-10 Verification

### ISSUE THREAD

**Issue by imhxc** [stellar/stellar-disbursement-platform-backend#348]
### Description:

We have encountered an issue with the user registration process in SDP. When an admin triggers a distribution task in the backend, new users receive a registration link. However, this link does not associate with the user's identity correctly. This leads to a discrepancy where the phone number bound to a wallet address in the SDP registration process does not match the phone number-wallet binding in our application.

This discrepancy creates confusion and inconsistencies in the user experience and data integrity across our applications.

### I believe the issue is caused by the following reasons:

1. The registration link (deeplink) that users receive is not associated with their identity. This leads to the problem where, when the user clicks the deeplink, I don't know which wallet address to use for SEP-10 verification.
2. During the SDP registration process, users can enter any phone number, which makes the association between the wallet address and phone number uncontrollable.

### Why?
Therefore, if my understanding of SDP is correct, could you please explain why this scenario was not considered in the design?

### Other
Additionally, I believe that during the distribution process, it should be allowed to directly input wallet addresses in the CSV file. This way, SDP can directly transfer funds to the provided wallet addresses, which seems to be a more reliable approach.

**Comment by Oyase-shinobi** [comment]
Hello
may I take this issue
I would love to contribute in this project

**Comment by marwen-abid** [comment]
@imhxc The registration link (deeplink) is not associated with a receiver. The identity of the receiver is resolved during the first step of the SEP24 process: 
* Receiver enters their phone number to get verified through an OTP
* We validate and resolve the receiver if the phone number exists in the CSV and the OTP is correct
* We associate the current wallet address to the receiver. 
More information can be found here [Initiate Sep 24 Webflow](https://developers.stellar.org/platforms/stellar-disbursement-platform/admin-guide/getting-started#initiate-sep-24-webflow)

If you feel like this doesn't answer the question, please send us steps to reproduce the bug and we will work on addressing that. 

> Additionally, I believe that during the distribution process, it should be allowed to directly input wallet addresses in the CSV file. This way, SDP can directly transfer funds to the provided wallet addresses, which seems to be a more reliable approach.

We have this feature on our backlog and we plan to add this capability in the next few months.

**Comment by marwen-abid** [comment]
> Hello may I take this issue I would love to contribute in this project

@Oyase-shinobi Until I get more clarification from @imhxc , I don't believe this is an actual issue. We would love to have contributions as we're a small team. Here is a good first issue if you're looking at contributing to the codebase https://github.com/stellar/stellar-disbursement-platform-backend/issues/102

**Comment by imhxc** [comment]
@marwen-abid 
Thank you for your response, but I still have a question:

In our existing platform, users have already registered with the following data:

Phone number
Stellar wallet address
How can we link these existing user data with SDP for fund distribution, ensuring that each user's phone number and wallet address always maintain a one-to-one relationship in these services?

**Comment by marwen-abid** [comment]
@imhxc it sounds like you need the "known wallet address" feature. This feature would allow you to upload a list of receivers with their phone number or email as well as their Stellar wallet addresses. So the stellar wallet address will be a new field in the CSV. 
This is useful for organizations that already have the list of addresses they want to disburse funds to. 

We will start working on it early October, so hopefully it will be added soon.

**Comment by marwen-abid** [comment]
@Oyase-shinobi @imhxc if you're interested in contributing to the SDP, "known wallet address" is a good feature to work on. I created an issue to describe the feature https://github.com/stellar/stellar-disbursement-platform-backend/issues/410

However, this feature is critical path for us. So if it is not completed by beginning of October we will have to pick it ourselves.

**Comment by Oyase-shinobi** [comment]
Hello @marwen-abid 
Thank you for your consideration
I have checked the issue and I have some question
can we chat in discord for fast communication?
